version: "3"

services:
  nv_mq:
    build: ./nv_mq
    container_name: nv_mq
    restart: unless-stopped
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - MQ_HOST=${MQ_HOST}
      - MQ_PORT=${MQ_PORT}
      - MQ_USER=${MQ_USER}
      - MQ_PASS=${MQ_PASS}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
    logging:
      options:
        max-size: 10m
    networks:
      - nvh-network

networks:
  nvh-network:
    external: true
